"""initial

Revision ID: 866dfcef6b2c
Revises:
Create Date: 2024-06-30 00:22:28.199540

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "866dfcef6b2c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinicians",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("registration_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_clinicians_registration_id"),
        "clinicians",
        ["registration_id"],
        unique=False,
    )
    op.create_table(
        "medications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("code_name", sa.String(), nullable=False),
        sa.Column("code_system", sa.String(), nullable=False),
        sa.Column("strength_value", sa.Integer(), nullable=False),
        sa.Column("strength_unit", sa.String(), nullable=False),
        sa.Column(
            "form",
            sa.Enum("powder", "tablet", "capsule", "syrup", name="medicationform"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "patients",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("sex", sa.Enum("male", "female", name="sex"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "medication_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("clinician_id", sa.Integer(), nullable=False),
        sa.Column("medication_id", sa.Integer(), nullable=False),
        sa.Column("reason_text", sa.Text(), nullable=False),
        sa.Column("prescribed_date", sa.Date(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("frequency_per_day", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "on_hold",
                "cancelled",
                "completed",
                name="medicationrequeststatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["clinician_id"],
            ["clinicians.id"],
        ),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medications.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_medication_requests_clinician_id"),
        "medication_requests",
        ["clinician_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_requests_medication_id"),
        "medication_requests",
        ["medication_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_medication_requests_patient_id"),
        "medication_requests",
        ["patient_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_medication_requests_patient_id"), table_name="medication_requests"
    )
    op.drop_index(
        op.f("ix_medication_requests_medication_id"), table_name="medication_requests"
    )
    op.drop_index(
        op.f("ix_medication_requests_clinician_id"), table_name="medication_requests"
    )
    op.drop_table("medication_requests")
    op.drop_table("patients")
    op.drop_table("medications")
    op.drop_index(op.f("ix_clinicians_registration_id"), table_name="clinicians")
    op.drop_table("clinicians")
    # ### end Alembic commands ###
